codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 85%
        threshold: 1%
        informational: false
    patch:
      default:
        target: 80%
        threshold: 2%
        informational: false

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "**/*.g.dart"
  - "**/*.freezed.dart"
  - "**/generated/**"
  - "test/**"
  - "build/**"
  - ".dart_tool/**"
